### ISSUE TITLE
Feature Request: Clickable URLs

### ISSUE THREAD

**Issue by condean** [squidowl/halloy#399] opened 2024-06-18 21:13 UTC
It would be nice if URLs were detected within chats and clickable or at least right-clickable or shift/alt clickable to open in browser. 

I'm on macOS Monterey if that makes a difference.

Loving Halloy! Thanks for an awesome client!

**Comment by casperstorm** [comment] 2024-06-19 08:36
Duplicate of https://github.com/squidowl/halloy/issues/75.
Trust me, we are implementing this feature as soon as the GUI framework we use gives us the opportunity!

**Closed by casperstorm** 2024-06-19 08:36 UTC
