### ISSUE TITLE
Input text buffer carries over when opening or re-opening a channel window

### ISSUE THREAD

**Issue by Tangdongle** [squidowl/halloy#103] opened 2023-07-06 08:34 UTC
To reproduce:

1. /join a channel
2. The channel now appears in the side pane. Enter some text into the input of the original channel
3. Click the newly joined channel to open up the window alongside the original channel
4. The channel window opens with the text already in the buffer

**Comment by ineeee** [comment] 2023-07-09 04:07
i can't reproduce it either. the text stays in the corresponding buffer in my client

**Comment by tarkah** [comment] 2023-07-10 23:08
Closing since this can't be reproduced

**Closed by tarkah** 2023-07-10 23:08 UTC
Labels: bug
