### ISSUE TITLE
setting [theme] and [tooltips] bug

### ISSUE THREAD

**Issue by Xanazf** [squidowl/halloy#335] opened 2024-04-13 00:53 UTC
@squidowl when you set `[theme]` or `[tooltips]` settings:
![image](https://github.com/squidowl/halloy/assets/56270904/13f81ec8-d928-4fad-aae8-b80d0ae06a2e)

 on launch Halloy returns an error like this:
![image](https://github.com/squidowl/halloy/assets/56270904/220785fb-f532-402b-aae7-61e2ec5ec52f)

![image](https://github.com/squidowl/halloy/assets/56270904/896f54f7-a819-49e4-bb9b-2edaa62b0b50)

## has been reproduced by bmillham on IRC

**Comment by bmillham** [comment] 2024-04-13 00:56
I can confirm with:

`[theme]
theme = 'mytheme`

I get the same error.

**Comment by tarkah** [comment] 2024-04-13 02:59
Looks like the wiki is confusing here. Both `theme` and `tooltips` are root keys for a string and boolean type respectively.

The wiki shows them as `[theme]` / `[tooltips]` sections which is inaccurate so we will need to fix that. @casperstorm

**Comment by bmillham** [comment] 2024-04-13 03:42
Important note: The theme and tooltips must be before any [] sections, otherwise they are part of a section (and do not cause an error)

**Comment by casperstorm** [comment] 2024-04-13 15:16
Fixed in https://github.com/squidowl/halloy/pull/336.

**Closed** 2024-04-13 20:18 UTC
Labels: bug, waiting on maintainer
