### ISSUE TITLE
Slow typing

### ISSUE THREAD

**Issue by krstp** [squidowl/halloy#397] opened 2024-06-18 20:08 UTC
The UI is not catching all the keyboard buttons on time. Such as if I type to fast it will miss on some typing. UI requires user to type relatively super slow in order to be able to type full words, otherwise singled out letters are missed.

**Comment by alpert1** [comment] 2024-06-30 10:22
I can confirm this issue and would add that it makes Halloy completely unusable. I try typing "that" and I'm lucky if Halloy even catches one letter of the word. This issue only occurs in active channels and therefore seems to be related to the processing of new messages by Halloy. As of right now Halloy is only usable in inactive channels, which makes it a pretty useless IRC client (but with a lot of potential, I'd like to add).

**Comment by casperstorm** [comment] 2024-07-01 12:00
I'll have a fix ready for you two to test within the next day. Will let you know when it's ready.

**Comment by casperstorm** [comment] 2024-07-01 19:29
Can you test the branch [fix/increase-batch-interval](https://github.com/squidowl/halloy/tree/fix/increase-batch-interval)?
I've attached the release versions of the branch below if you don't want to compile yourself. If you compile yourself, remember to run it with `--release`.

Let me know if this feels better/worse.

[halloy-2024.7-x86_64-linux.tar.gz](https://github.com/user-attachments/files/16058248/halloy-2024.7-x86_64-linux.tar.gz)

**Comment by alpert1** [comment] 2024-07-01 19:34
Could you please attach a portable Windows version? While [krstp](https://github.com/krstp) is running Halloy on Ubuntu, I'm using it on Windows 10.

**Comment by casperstorm** [comment] 2024-07-01 19:43
> Could you please attach a portable Windows version? While [krstp](https://github.com/krstp) is running Halloy on Ubuntu, I'm using it on Windows 10.

Yes, but its a .msi as thats what our CI provides: [halloy-installer.msi.zip](https://github.com/user-attachments/files/16058367/halloy-installer.msi.zip)

**Comment by alpert1** [comment] 2024-07-01 20:18
It's far better than before, but Halloy is still dropping letters every now and then. I am retracting my hunch of it being related to incoming messages though, as the issue also occurs in inactive channels and didn't seem to be that much more prominent in the active channel now, though that channel was less active now than during my initial test. I'm guessing that the fix only changed a refresh interval, but the underlying bug, which makes Halloy drop letters to begin with, is still there, just not as noticeable than with the higher interval.

**Comment by krstp** [comment] 2024-07-01 22:23
@casperstorm It is still buggy. Writing forward somewhat works (the key repeatability seems kind of slow compared to other windows). Needless to say, after writing some text, then afterwards pushing quickly (in sustained manner, pushed in button key) `backspace/delete` the same bug appears. I hope this helps.

**Comment by casperstorm** [comment] 2024-07-11 18:29
@alpert1 and @krstp,
Are you able to compile Rust projects? If yes, could you try the following:

```sh
git clone https://github.com/iced-rs/iced.git
cd iced/examples/tour
cargo run --release
```

This should compile a small Iced example, the underlying GUI framework we use, which has a text input. I am curious if you see any letters dropped there as well, or if thats smooth.

**Comment by krstp** [comment] 2024-07-11 21:51
Verified. `iced` seems to work as desired. no delays, slowdowns, or shifts.

**Comment by tarkah** [comment] 2024-07-14 18:22
Dropped characters are 100% fixed by https://github.com/squidowl/halloy/pull/414

**Closed** 2024-07-15 19:19 UTC
Labels: bug, performance
